name: CI

on: [push, pull_request]

jobs:
    build-packages:
        name: Build and Test ${{ matrix.package }}
        strategy:
            matrix:
                package:
                    - sushii-2
                    - sushii-api
                    - sushii-model
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Select toolchain
              id: toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-test-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

            - name: Build ${{ matrix.package }}
              uses: actions-rs/cargo@v1
              working-directory: ${{ matrix.package }}
              with:
                  command: build

            - name: Test ${{ matrix.package }}
              uses: actions-rs/cargo@v1
              working-directory: ${{ matrix.package }}
              with:
                  command: test
